spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      connection-timeout: 60000

  data:
    cassandra:
      contact-points:
        - host.docker.internal:9042
        - host.docker.internal:9043
        - host.docker.internal:9044
      keyspace-name: thiscode
      schema-action: create_if_not_exists
      #      username: cassandra
      #      password: cassandra
      local-datacenter: datacenter1

  application:
    name: monitoring

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  metrics:
    tags:
      application: ${spring.application.name}