spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      connection-timeout: 60000

  data:
    mongodb:
      uri: ENC(2u0JlOLPDK4xLFjqT7eN/ZmrWw8DOL9izKVLasjABBjkg2Q2B+Ep2PYD4iJEGYhgTXPF3ZXIiRuk8mIBL4QXbz+4Pvj6L4KGYgCF3n7X1yv1DvELF+S6AmrStMIOPyNz10sdoVZE2zY=)
      auto-index-creation: true

  application:
    name: monitoring

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  metrics:
    tags:
      application: ${spring.application.name}