spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      connection-timeout: 60000
    url: ENC(AtbAmjmXqguvVjtmxT14rzHAGZXtPCNJJ/VUUG7ajPBIGeY/tCv9Dht1wHSnTu4xRD1qFg0jI2J3+4Kky0ZeXYY7CmzGw8RI9/VJuDR4vReoyTkWgVtqEVbd0v2EJNiQRbK+XW1vy3hdZ3wluhgFU7SZZCsAjwM+u2v5S76msntjxsDpjHU7qdrShxqjX3H67+0X59IZjqjr6HPMRjFYhQ==)
    username: ENC(nZEFzHuwF4wasrpbc2TcJQ==)
    password: ENC(mJyIfhz6z46U9Q4Exy4LQamYMyEBiJiG)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update

  data:
    cassandra:
      contact-points:
        - host.docker.internal:9042
        - host.docker.internal:9043
        - host.docker.internal:9044
      keyspace-name: thiscode
      schema-action: create_if_not_exists
      #      username: cassandra
      #      password: cassandra
      local-datacenter: datacenter1

  application:
    name: monitoring

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  metrics:
    tags:
      application: ${spring.application.name}