spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ENC(czihp9Turnh3T8SihZ2FyvoPE9ZFhrUjGZKV7e/DTqBIVOeN9w0UthrnVWfTKWS/B3ZvbRRDzDFCFJf02wg9NuWC9v4mjPUhIozbs4KlyAOSevVLYsz3PF3mZe9oJvFgxkipehdGQF8Hm01zNWTd0A==)
    username: ENC(NtuvZQCkv8WSkzoBv7CoiQ==)
    password: ENC(FW0F58KfaI/pVjnKCHgd2urr848cdss4)
    driver-class-name: ENC(Jr0OQfMUL92AZUp2tg0sucokFdBsxYkrX7YNAvIUVO59xLBT672k7A==)