spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      connection-timeout: 60000

  data:
    mongodb:
      uri: mongodb+srv://admin:chat1122@thiscode.cpaiaoh.mongodb.net/thiscode?retryWrites=true&w=majority
      auto-index-creation: true

  rabbitmq:
    host: rabbitMQ
    port: 5672
    username: guest
    password: guest

  application:
    name: monitoring

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  metrics:
    tags:
      application: ${spring.application.name}
