spring:
  config:
    activate:
      on-profile: local
  data:
    cassandra:
      contact-points:
        - 34.64.79.69:9042
      keyspace-name: thiscode
      schema-action: create_if_not_exists
#      username: cassandra
#      password: cassandra
      local-datacenter: datacenter1
